general refactoring of db_app
classifiedfear/tg_bot_float pull request #1
Opened 2024-04-22 13:05 UTC by classifiedfear

2024-04-27 09:05 UTC, aannenko reviewed
A great PR! Many things are made much better! I love the new absolute imports instead of the relative ones!

One question though: do we still need `__init__.py` files?

2024-04-27 09:05 UTC, aannenko commented on src/tg_bot_float_scheduler_app/db_updater/db_updater.py
> +from tg_bot_float_service.services.cs_skins_data_retriever.skin_data_retriever import CsInfoService
If the scheduler app depends on some other apps, let's maybe not add the scheduler app until those apps are added? Otherwise we make our code base disfunctional for the duration when scheduler is in the code base and its dependencies are not.

2024-04-27 12:09 UTC, aannenko commented on src/tg_bot_float_db_app/database/services/weapon.py
>      async def get_many_by_id(self, ids: typing.List[int]):
My apologies, this method actually should work as advertised. Please ignore this comment.

2024-04-27 13:22 UTC, aannenko requested changes
Please act on my comments, commit and push the changes and then request my review again :)

2024-04-29 07:16 UTC, classifiedfear reviewed
> May I suggest replacing this with `from sqlalchemy.ext.asyncio import AsyncEngine, async_sessionmaker` and then correcting these types' usages below? 

Done!

2024-05-01 19:40 UTC, aannenko commented on src/tg_bot_float_db_app/routers/skin.py
> +        skin_db_model.name = skin_post_model.name
I believe this suggestion has not been fully addressed.

Let's consider the case when we want to update only the `stattrak` of a skin. How do we do that? We can fill this DTO with all possible data for the skin (`name` and `stattrak`), send it to `SkinQueryService.update_by_id` and it will perform an update of both `name` and `stattrak`. But let's imagine we only have the skin's `stattrak` at our disposal and the `name` is not available, which is quite a common case in any distributed architecture. In this case we cannot create a correct object of `SkinDTO` because we're missing the `name`. So we cannot perform an update in this case, right?

The solution would be to fill the DTO partially (only `stattrak`) and make it capable of conveying which variables in it are actually set.
Example (similar to the one in my previous comment, updated according to the latest changes):
```python
class SkinDTO(BaseModel):
    id: int = 0
    name: str | None = None
    stattrak_existence: bool | None = None
```
In this case we can only put `stattrak` in it. And when the method `SkinQueryService.update_by_id` receives such object, it will have to check which values are not `None` and perform a database update only for those.

2024-05-01 19:45 UTC, aannenko commented on src/tg_bot_float_common_dtos/skin_dto.py
> +class SkinDTO(BaseModel):
I elaborated on this in the "complex suggestion" comment for the skins router, I'll also leave a similar but shorter suggestion here.
Let's make this DTO class capable of saying "The variables that are not `None` need to be processed. Do not use variables with `None` values."
```python
class SkinDTO(BaseModel):  
    id: int = 0  
    name: str | None = None  
    stattrak_existence: bool | None = None
```

2024-05-01 20:45 UTC, aannenko commented on src/tg_bot_float_db_app/database/db_factory.py
> +        async with BotDbServiceFactory(BotDbFactory._engine) as service_factory:
There may be certain problems with this pattern of creating an object of a class as a context manager and then yielding this object to the caller.
https://stackoverflow.com/questions/41881731/is-it-safe-to-combine-with-and-yield-in-python

2024-05-01 20:48 UTC, aannenko commented on src/tg_bot_float_db_app/api/routers/db_router.py
> +DB_ROUTER = fastapi.APIRouter(prefix="/db", tags=["db"])
I would suggest that we refrain from writing python files with functions directly in them and instead put those functions inside classes.
For example it would help us in the future when we need to pass loggers to constructors of these classes.

2024-05-01 20:53 UTC, aannenko commented on src/tg_bot_float_db_app/api/dependencies/service_factory.py
> +ServiceFactory = Annotated[BotDbServiceFactory, Depends(BotDbFactory.get_service_factory)]
Let's rename `ServiceFactory` to `DbServiceFactory` so that the people reading the routers' code would know what that factory in each router method really is.
In the future we may have other service factories and we will need to distinguish them somehow.

2024-05-01 20:58 UTC, aannenko commented on src/tg_bot_float_db_app/api/utils.py
> +async def lifespan(app: FastAPI):
Please place this method inside `main.py` - it will be easier to read it from there.
Also, as I understand, FastAPI expects such methods to return `AsyncContextManager` and this method actually returns `AsyncGenerator[None, Any]`.

2024-05-07 06:49 UTC, aannenko commented
For the future (not for this PR).
Status codes are an important part of any API app. They should be returned correctly for the app's endpoints.

For example:
1. When a POST endpoint `create` was called and if the operation finished successfully, the endpoint should return a response with the status 201 (Created).
2. When a GET endpoint `get_by_id` is called and the item could not be found by its id, the endpoint should return a response with the status code 400 (Bad Request) and the appropriate response message. The same is true for PUT `update_by_id`.

Feel free to create an issue in this repository which would describe the problem. Then in the future you will be able to address this problem in a separate pull request.

2024-05-07 10:20 UTC, aannenko requested changes
We move closer and closer to a high quality code :)
Thanks for your effort and keep up the good work!

2024-05-07 10:20 UTC, aannenko commented on src/tg_bot_float_db_app/database/models/user_subscription_model.py
> +user_subscription = Table(
Do we really need this mapping table declared in our code?
AFAIK, if we have correctly configured relation properties in the `UserModel` and `SubscriptionModel`, this table may be created automatically for us by SQLAlchemy.

2024-05-07 10:20 UTC, aannenko commented on src/tg_bot_float_db_app/database/services/bot_db_refresher_service.py
> +        weapon_dtos_to_create = {weapon.name: weapon for weapon in weapons}
The type of `weapon_dtos_to_create` is `dict[str | None, WeaponDTO]`. Can we change list comprehension here so that we had the type was `dict[str, WeaponDTO]`?
This way we will fix the analyzer error on the line with the return statement.

2024-05-07 10:20 UTC, aannenko commented on src/tg_bot_float_db_app/database/services/bot_db_refresher_service.py
> +        skin_dtos_to_create = {skin.name: skin for skin in skins}
Let's fix dictionary comprehension here so that it was returning `dict[str, SkinDTO]`

2024-05-07 10:20 UTC, aannenko commented on src/tg_bot_float_db_app/database/services/bot_db_refresher_service.py
> +        quality_dtos_to_create = {quality.name: quality for quality in qualities}
Let's fix dictionary comprehension here so that it was returning `dict[str, QualityDTO]`

2024-05-07 10:20 UTC, aannenko commented on src/tg_bot_float_db_app/api/routers/quality_router.py
> +                existence_quality_db_models = await quality_service.get_many_by_id(ids)
Let's move this functionality to the service class. It should not be the responsibility of the router.

2024-05-07 10:20 UTC, aannenko commented on src/tg_bot_float_db_app/api/routers/quality_router.py
> +                existence_quality_db_models = await quality_service.get_many_by_name(names)
Let's move this logic to the service.

2024-05-07 10:20 UTC, aannenko commented on src/tg_bot_float_db_app/api/routers/skin_router.py
> +                existence_skin_db_models = await skin_service.get_many_by_name(names)
Let's move this logic to the service class.

2024-05-07 10:20 UTC, aannenko commented on src/tg_bot_float_db_app/api/routers/skin_router.py
> +                existence_skin_db_models = await skin_service.get_many_by_id(ids)
Let's move this logic to the service class.

2024-05-08 12:40 UTC, aannenko commented on src/tg_bot_float_db_app/misc/exceptions.py
> +class BotDbException(Exception):
1. Usually custom exceptions have constructors with parameters which indicate how these exceptions should be instantiated.
2. In our case, I'd go with only one constructor parameter called `message`. The callers, when they want to raise this exception, will need to prepare a message and then pass it to the exception's constructor.

2024-05-08 12:42 UTC, aannenko commented on src/tg_bot_float_db_app/misc/msg_response_dto.py
> +class MsgResponseDTO(BaseModel):
Maybe it would be a good idea to put class variables into a constructor.

2024-05-08 20:33 UTC, aannenko reviewed
Because our code grows, we need a set of rules that will describe how our code should be written. So far the best way to do this is to add a file `.editorconfig` to the `src` directory. It will describe some of the rules.

Because currently we only have .py files in our repository, the contents of such an `.editorconfig` could be the following:
```
# EditorConfig is awesome: http://EditorConfig.org

# top-most EditorConfig file
root = true

# Tab indentation
[*]
indent_style = space
indent_size = 4
trim_trailing_whitespace = true
insert_final_newline = true
```
We then can [expand](https://editorconfig.org/) our `.editorconfig` as we add more file types to the repo.

2024-05-12 09:02 UTC, aannenko requested changes
Nice set of changes! The code is almost problem-free now. Mostly the "quality of life" improvements are suggested. :)

2024-05-18 10:05 UTC, aannenko reviewed
Routers are so clean now! That's awesome!

2024-05-18 10:05 UTC, aannenko commented on src/tg_bot_float_db_app/misc/exceptions.py
> +class BotDbException(Exception):
Let's call the file bot_db_exception.py

2024-05-18 10:06 UTC, aannenko requested changes
Only a couple of minor changes left and then we can finally merge this PR!

2024-05-18 10:30 UTC, classifiedfear commented on src/tg_bot_float_db_app/api/routers/skin_router.py
> +            return list(await skin_service.get_all())
Type "List" cannot be instantiated, so i need to use list

2024-05-18 10:32 UTC, aannenko commented on src/tg_bot_float_db_app/api/routers/skin_router.py
> +            return list(await skin_service.get_all())
My bad :)

2024-05-18 12:00 UTC, aannenko approved these changes

2024-05-18 12:01 UTC, merged