DB updater service project
classifiedfear/tg_bot_float pull request #14
Opened 2024-06-09 10:20 UTC by classifiedfear

Added Db updater service project

2024-06-15 12:21 UTC, aannenko requested changes

2024-06-15 16:13 UTC, aannenko commented
Let's convert this project into a standalone microservice, with its own API, Dockerfile and requirements.txt

2024-06-20 18:37 UTC, aannenko requested changes
Good quality code!
There's only a handful of minor problems.

2024-06-22 06:21 UTC, classifiedfear commented on src/tg_bot_float_db_app/Dockerfile
> +COPY settings/ settings/
File csgo_db_source_settings.py does not belongs to src/tg_bot_float_db_app/. This settings need to be in src/tg_bot_float_csgo_db_source/. So I move it to tg_bot_float_csgo_db_source/.

2024-06-22 11:14 UTC, classifiedfear commented on src/tg_bot_float_db_app/Dockerfile
> +COPY settings/ settings/
Maybe, I need to do it different branch? With changes suggested in #12 ?

2024-06-22 14:23 UTC, aannenko commented on src/tg_bot_float_db_app/Dockerfile
> +COPY settings/ settings/
> Maybe, I should do it in different branch? With changes suggested in #12 ?

Makes sense, please do :)

2024-06-29 11:15 UTC, aannenko requested changes
Good job on the last update of this PR, I still have some suggestions though :)

2024-06-29 11:15 UTC, aannenko commented on src/tg_bot_float_db_updater/dependencies/services.py
> +    db_data_getter_service = DbSourceDataGetterService(settings)
Let's simplify the body of this method to the following form:
```python
async with DbSourceDataGetterService(settings) as db_data_getter_service:
    db_data_sender_service = DbDataSenderService(settings)
    db_updater_service = DbDataUpdaterService(db_data_getter_service, db_data_sender_service)
    yield db_updater_service
```
It should work the same (I tested) and will also let us get rid of the `ClientSession` initialization in `DbSourceDataGetterService.__init__`.

2024-06-29 11:15 UTC, aannenko commented on src/tg_bot_float_db_updater/db_updater_service/db_source_data_getter_service.py
> +    async def get_csm_wiki_skin_data(self, weapon: str, skin: str) -> Dict[str, Any]:
In order to make the returned data more understandable, lets not return a dictionary but instead let's return an object of some (new, likely) DTO class that will contain this data.
E.g. we could return an object of something like this from this method:
```python
from pydantic import BaseModel, ConfigDict

class CsmWikiDTO(BaseModel):
    model_config = ConfigDict(from_attributes=True)
    qualities: List[str]
    stattrak_existence: bool
```

Note! Because we will only be using this DTO in this project, let's have the file with it somewhere in this project's folder, e.g. in `tg_bot_float_db_updater/dtos` and not in the `tg_bot_float_common_dtos`.

2024-06-29 13:26 UTC, aannenko commented on src/tg_bot_float_db_updater/db_updater_service/db_data_sender_service.py
> +                assert response.status in list(range(200, 300))
We should probably cache this list of status codes in the object - it should not be created every time this method is executed.
Let's create a static (class-level) variable with the allowed status codes.

2024-06-29 13:30 UTC, aannenko commented on src/tg_bot_float_db_updater/db_updater_service/db_source_data_getter_service.py
> +class DbSourceDataGetterService:
We should probably split this service into two separate ones: one for csgodatabase, the other for csm wiki.

2024-11-04 20:25 UTC, aannenko approved these changes

2024-12-20 12:40 UTC, aannenko commented
This PR is approved, feel free to merge :)

2024-12-29 14:40 UTC, merged

2024-12-29 17:17 UTC, aannenko reviewed
If you ask people to review your PRs, please don't merge them until they finish reviewing your code and until you fix all the problems they've pointed out.